# Generated by Django 3.2 on 2022-09-11 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_liketweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='DislikeTweet',
            fields=[
                ('liketweet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.liketweet')),
            ],
            bases=('post.liketweet',),
        ),
    ]
