# Generated by Django 3.2 on 2022-09-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_disliketweet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DislikeTweet',
        ),
    ]
