# Generated by Django 3.2 on 2022-09-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_likedisliketweet_tweetstatus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liketweet',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='liketweet',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='liketweet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dis_LikeComment',
        ),
        migrations.DeleteModel(
            name='LikeTweet',
        ),
    ]
