# Generated by Django 3.2 on 2022-09-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20220914_2142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TweetStatus',
            new_name='Status',
        ),
    ]
