# Generated by Django 3.2 on 2022-09-14 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_dislikecomment_likecomment_likedislikecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('status_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='likedislikecomment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.statuscomment'),
        ),
    ]
