# Generated by Django 3.2 on 2022-09-14 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20220914_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislikecomment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.status'),
        ),
        migrations.DeleteModel(
            name='StatusComment',
        ),
    ]
